### ISSUE TITLE
Using oncoanalyser for whole exome sequencing data

### ISSUE THREAD

**Issue by anshupas** [nf-core/oncoanalyser#109]
I  have whole exome sequencing data from tumor and their matched normal samples. Can I use oncoanalyser to process this data e.g. by setting the mode to wgts?

**Comment by p-priestley** [comment]
We would recommend that you run oncoanalyser in targeted mode using resources trained for your specific exome panel (which may differ across vendors). An overview is described here:

https://github.com/hartwigmedical/hmftools/blob/master/pipeline/README_TARGETED.md

Which exome kit are you using?  We may be able to help provide some pre-trained resouces.  If you are interested please email me at p.priestley@hartwigmedicalfoundation.nl

**Comment by anshupas** [comment]
Thanks for clarifying. We are interested in using oncoanalyser for whole exome sequencing data, I have emailed you the relevant details regarding this.

**Comment by scwatts** [comment]
Closing this issue as resolved, thanks for fielding @p-priestley
