### ISSUE TITLE
Add low coverage filter settings for SAGE 

### ISSUE THREAD

**Issue by jaesvi** [nf-core/oncoanalyser#2]
### Description of feature

The default SAGE soft-filtering parameters are optimized for 100x tumor sequencing depth. A recommended set of soft-filtering parameters for lower depth samples is available at https://github.com/hartwigmedical/hmftools/blob/master/sage/README.md#5-soft-filters . 
I suggest introducing a low-depth parameter to optimize SAGE filtering. It could be either automatically detected from bamtools output (e.g. when average depth is <50x), or provided as a parameter by the user.

**Comment by scwatts** [comment]
An option to set well-defined configuration for lower depth tumour sequencing data seems useful.

Starting with just a simple switch (e.g. `--low_coverage`) is probably sufficient for most cases, and where that might fall short users can provide their own NF config to manually set SAGE parameters instead.

Let's avoid automated depth detection for now - I worry that it adds a fair amount of complexity for a feature that might not be widely used and may introduce unexpected behaviour for users unaware of it.

There is also a shallow mode in Pv5 though I think the intended use is different to running oncoanalyser with ≤50x tumour samples. I'll follow up with Hartwig to clarify and for any recommendations, then we can go from there.

/cc @charlesshale

**Comment by jaesvi** [comment]
I completely agree.

**Comment by p-priestley** [comment]
FYI - In 5.35 SAGE will be upgraded to a depth independent model (ie no need for changes of parameters at 30x). This will be available in Q2 somewhere

**Comment by scwatts** [comment]
Good to know, thanks for following this up Peter.

@jaesvi okay to close this issue and wait for the hmftools v5.35 release?

**Comment by jaesvi** [comment]
Yes, I think it is then not worth the effort at the moment.
