### ISSUE TITLE
task: name=NFCORE_ONCOANALYSER:WGTS:READ_ALIGNMENT_RNA:STAR (1); work-dir=null

### ISSUE THREAD

**Issue by taijiyamazoe** [nf-core/oncoanalyser#44]
### Description of the bug

When I run the nf-core/oncoanalyser, I got the error about work-dir=null for STAR and FASP.
So I add the folllowing lines to the modules.config.
But the error comes again.
I think I have to edit the config in right way, but I can not figure out so far.
I am grateful if you give me suggestions.
Thanks,

the lines I added to modules.config

    withName: 'NFCORE_ONCOANALYSER:WGTS:READ_ALIGNMENT_RNA:STAR' {
        publishDir = [
            path: { "${params.outdir}" },
            mode: params.publish_dir_mode,
            saveAs: { filename -> filename.equals('versions.yml') ? null : "${meta.key}/alignments/rna/${filename}" },
        ]
    }
    
    withName: 'NFCORE_ONCOANALYSER:WGTS:READ_ALIGNMENT_DNA:FASTP' {
        publishDir = [
            path: { "${params.outdir}" },
            mode: params.publish_dir_mode,
            saveAs: { filename -> filename.equals('versions.yml') ? null : "${meta.key}/alignments/dna/${filename}" },
        ]
    }

### Command used and terminal output

```console
execute:

nextflow run nf-core/oncoanalyser \
   -revision 0.4.5 \
   -profile docker \
   --mode wgts \
   --genome GRCh38_hmf \
   --input /mnt/ssd2T/reference/Nextflow/nf_sample.csv \
   --outdir /home/owner/data


error:

Execution cancelled -- Finishing pending tasks before exit
-[nf-core/oncoanalyser] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_ONCOANALYSER:WGTS:READ_ALIGNMENT_DNA:FASTP (1)'

Caused by:
  Path value cannot be null
```

**Comment by scwatts** [comment]
Hi @taijiyamazoe, can you please attach your `nf_sample.csv` samplesheet and also confirm that all files provided in it exist?

**Comment by taijiyamazoe** [comment]
Awww. So embarrassed. I had given only R1.fastq but not with R2.
It went through that point when I set R1.fastq;R2.R2fastq in my samplesheet.csv.
Thank you for noticing me the mistake in the VERY FAIRST step.

But I got another error, no fastp command...
I thought the nextflow can automatically download the necessary pipelines when the program is not available in the user environment.
Should I set up manually all of the necessary program like fastp, STAR, bwa and so on? or Only fastp is good enough?

**Comment by scwatts** [comment]
No worries! I'm planning to improve samplesheet checking to make it clear when this happens, it's not very obvious at the moment.

The required software (e.g. fastp, bwa-mem2, STAR, etc) should be automatically downloaded by oncoanalyser if you set `-profile docker` for example.

Can you provide describe how you're running oncoanalyser, the command you're using, and the `.nextflow.log` as well?

**Comment by taijiyamazoe** [comment]
Hi @scwatts , Thanks a lot!

Actually I want to build this for the offline mode under conda evironment.
I download the reference data (like STAR index 2.7.3a etc...)
and I run like the following script.
Now my PC finally starts smoking to do so!
before that, I should install fastp and STAR==2.7.3a (compatible for reference data which STAR latest does not like) and edit module config to add "command zcat option" for my fq.gz data.
probably I will be asked to download the other program later...





#!/bin/bash

outdir='/home/owner/data/'
source /home/owner/miniconda3/etc/profile.d/conda.sh
conda activate env_nf

cd ${outdir}
nextflow run /home/owner/nf-core-oncoanalyser_0.4.5/0_4_5 \
  -profile conda \
  --mode wgts \
  -config /mnt/ssd2T/reference/Nextflow/refdata.local.config \
  --genome GRCh38_hmf \
  --genome_version 38 \
  --genome_type no_alt \
  --input /mnt/ssd2T/reference/Nextflow/nf_sample.csv \
  --outdir ${outdir}


refdata.local.config:
params {
 
    genomes {
        GRCh38_hmf {
            fasta           = "/mnt/ssd2T/reference/Nextflow/GRCh38/FASTA/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
            fai             = "/mnt/ssd2T/reference/Nextflow/GRCh38/FASTA/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.fai"
            dict            = "/mnt/ssd2T/reference/Nextflow/GRCh38/FASTA/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.dict"
            bwa_index       = "/mnt/ssd2T/reference/Nextflow/GRCh38/bwa_index_0.7.17-r1188/"
            bwa_index_bseq  = "/mnt/ssd2T/reference/Nextflow/GRCh38/bwa-mem2_index_2.2.1/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.0123"
            bwa_index_biidx = "/mnt/ssd2T/reference/Nextflow/GRCh38/bwa-mem2_index_2.2.1/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bwt.2bit.64"
            bwa_index_image = "/mnt/ssd2T/reference/Nextflow/GRCh38/bwa_index_0.7.17-r1188/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.img"
            gridss_index    = "/mnt/ssd2T/reference/Nextflow/GRCh38/gridss_index_2.13.2/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gridsscache"
            star_index      = "/mnt/ssd2T/reference/Nextflow/GRCh38/star_index_38_2.7.3a/"
        }
    }
 
    ref_data_hmf_data_path        = "/mnt/ssd2T/reference/Nextflow/GRCh38/hmftools_5.34_38--2/"
    ref_data_panel_data_path      = "/mnt/ssd2T/reference/Nextflow/GRCh38/panels_tso500_5.34_38--1/"
    ref_data_virusbreakenddb_path = "/mnt/ssd2T/reference/Nextflow/virusbreakenddb_20210401/"
}

**Comment by taijiyamazoe** [comment]
I dig the directory modules/local a little bit.
There is a series of directory for every single programs which has environment.yml
According to them, I can download the necessary program manually.
But star and fastp do not the environment.yml
Are there any correlation with my problem or just conda does not support automatically downloading all of them?

Oops, I got another error, I must download GATK (markdups) for her...

**Comment by scwatts** [comment]
Unfortunately the 0.4.5 version has incomplete Conda support as you've seen. There is better Conda support in the `dev` branch but switching to that from `0.4.5` requires reorganisation of reference data (see [here for new layout](https://github.com/nf-core/oncoanalyser/blob/b0cf4ceb2c42cf037ba2009d008730b05b4a04aa/conf/hmf_genomes.config)). I would strongly recommend using Docker or Singularity if at all possible.

Otherwise you can try grabbing the `environment.yml` files from the dev branch (e.g. [STAR align](https://github.com/nf-core/oncoanalyser/blob/dev/modules/local/star/align/environment.yml), [MarkDups](https://github.com/nf-core/oncoanalyser/blob/dev/modules/local/markdups/environment.yml), etc).

There is also a fix for MarkDups and Sambamba coming in the next week that will greatly improve run times, so it might be worth waiting for that.

**Comment by taijiyamazoe** [comment]
Hi @scwatts , Thank you for providing the place holding yml files.

I encountered the version conflict issues around r-chord, r-base, icu, etc...
And I understand this is dev version.
So I now decided to switch the environment to Docker from conda as you suggest.

I appreciate that you guys make tremendous efforts to this great tools,
and am waiting for the upcoming update!

Best,

**Comment by scwatts** [comment]
I'm not surprised you're encountering conflicts trying to create a single Conda environment with all dependencies required, using Docker is a much better approach - glad to hear you've switched!

I'll close this issue for now but please reopen it (or create a new one) if needed.
