### ISSUE TITLE
Gene fusion detection

### ISSUE THREAD

**Issue by bounlu** [nf-core/oncoanalyser#63]
### Description of feature

Please add gene fusion events detection from DNA-Seq data.

**Comment by scwatts** [comment]
Hi @bounlu, gene fusion detection for DNA data is already available through [LINX](https://github.com/hartwigmedical/hmftools/tree/master/linx) for both WGS and targeted sequencing inputs.

**Comment by bounlu** [comment]
I see, in that case it would be nice to add the keyword `fusion` somewhere in the [documentation](https://nf-co.re/oncoanalyser/dev/).

**Comment by scwatts** [comment]
Thanks for the feedback, I'll include some reference to fusion detection.
