### ISSUE TITLE
Add support for custom targeted panel

### ISSUE THREAD

**Issue by bounlu** [nf-core/oncoanalyser#66]
### Description of feature

Currently the pipeline only supports `tso500` panel for the `targeted` analysis with the pre-computed reference files given in the `panel_data.config`. It would be nice to allow custom panels and documentation how to prepare the corresponding reference files:

```
driver_gene_panel
sage_actionable_panel
sage_coverage_panel
pon_artefacts
target_region_bed
target_region_normalisation
target_region_ratios
target_region_msi_indels
isofox_tpm_norm
isofox_gene_ids
isofox_counts
isofox_gc_ratios
```

**Comment by bounlu** [comment]
Thanks so much for pointing me to the available docs.

I think adding a step to the pipeline for generation of custom panel resource files would be great, just like you did for [staging reference data](https://nf-co.re/oncoanalyser/dev/docs/usage/#staging-reference-data), something like:

```
nextflow run nf-core/oncoanalyser \
  -profile docker \
  -revision dev \
  --mode wgts \
  --genome GRCh38_hmf \
  --prepare_custom_reference_only \
  --custom_panel_regions custom_panel_regions.bed \
  --custom_msi_sites custom_msi_sites.bed \
  --custom_driver_genes custom_driver_genes.tsv \
  --input samplesheet.csv \
  --outdir prepare_reference/
```

**Comment by scwatts** [comment]
No worries! And I totally agree with your suggestion - we've discussed plans for implementing the feature you've described.

**Comment by bounlu** [comment]
Hi @scwatts 

Would you be able to provide more information how to prepare the **Driver Gene Panel** file for custom panels?

For example, what do the column headers mean exactly and how are they used in the pipeline?
```
reportMissense
reportNonsense
reportSplice
reportDeletion
reportDisruption
reportAmplification
reportSomaticHotspot
likelihoodType
reportGermlineVariant
reportGermlineHotspot
reportGermlineDisruption
additionalReportedTranscripts
reportPGX
InPanel
```

How are the values different than the original panel doc in case of [TSO500](https://sapac.illumina.com/content/dam/illumina-marketing/documents/products/gene_lists/gene_list_trusight_oncology_500.xlsx)?
