### ISSUE TITLE
invalid file type: 'fastq' 

### ISSUE THREAD

**Issue by jkneppers** [nf-core/oncoanalyser#89]
### Description of the bug

Hi,

I'm trying to run oncoanalyser for the first time. I am using the test samplesheet.csv, which specifies dummy fastq.gz files for normal  and tumor DNA, and RNA. These are categorized as 'fastq' in the filetype column.

However, after running the command below, I'm getting the output invalid file type: 'fastq'. 
![image](https://github.com/user-attachments/assets/99b55077-ee93-4146-9c09-6500574980ca)

I am currently bound to nextflow version v22.04.3, this could be an issue as it is incompatible with the dev version, but I am getting nextflow outputs for -r v0.3.1. Am I missing something else?

Thanks,
J

### Command used and terminal output

```console
nextflow run nf-core/oncoanalyser \
  -profile docker \
  -revision v0.3.1 \
  --mode wgts \
  --genome GRCh37_hmf \
  --input /path/wgs/samplesheet.csv \
  --outdir /path/wgs/result_calls/
```

### Relevant files

Aug-20 13:41:48.355 [main] DEBUG nextflow.cli.Launcher - $> nextflow run nf-core/oncoanalyser -profile docker -revision v0.3.1 --mode wgts --genome GRCh37_hmf --input /path/N2N_mock/wgs/samplesheet.csv --outdir /path/N2N_mock/wgs/result_calls/ -resume
Aug-20 13:41:48.460 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 22.04.3
Aug-20 13:41:49.892 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/crunchshell/.nextflow/assets/nf-core/oncoanalyser/.git/config; branch: master; remote: origin; url: https://github.com/nf-core/oncoanalyser.git
Aug-20 13:41:49.906 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/crunchshell/.nextflow/assets/nf-core/oncoanalyser/.git/config; branch: master; remote: origin; url: https://github.com/nf-core/oncoanalyser.git
Aug-20 13:41:50.652 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/crunchshell/.nextflow/assets/nf-core/oncoanalyser/nextflow.config
Aug-20 13:41:50.653 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/crunchshell/.nextflow/assets/nf-core/oncoanalyser/nextflow.config
Aug-20 13:41:50.664 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `docker`
Aug-20 13:41:50.983 [main] DEBUG nextflow.plugin.PluginsFacade - Using Default plugins manager
Aug-20 13:41:51.000 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Aug-20 13:41:51.001 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Aug-20 13:41:51.005 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Aug-20 13:41:51.010 [main] DEBUG nextflow.plugin.PluginsFacade - Using Default plugins manager
Aug-20 13:41:51.860 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [bih, cfc_dev, uzl_omics, ifb_core, embl_hd, denbi_qbic, alice, mjolnir_globe, uppmax, incliva, ilifu, uge, rosalind_uge, lugh, mccleary, unibe_ibu, vai, czbiohub_aws, jax, ccga_med, scw, unc_longleaf, tigem, tubingen_apg, google, apollo, ipop_up, vsc_calcua, pdc_kth, googlels, daisybio, eddie, medair, biowulf, bi, bigpurple, adcra, cedars, pawsey_setonix, vsc_kul_uhasselt, pawsey_nimbus, ucl_myriad, utd_ganymede, charliecloud, icr_davros, ceres, munin, rosalind, hasta, cfc, uzh, ebi_codon_slurm, ebc, ccga_dx, crick, ku_sund_danhead, marvin, biohpc_gen, shifter, mana, mamba, york_viking, unc_lccc, wehi, awsbatch, wustl_htcf, arcc, imperial, maestro, software_license, genotoul, nci_gadi, abims, janelia, nu_genomics, googlebatch, oist, sahmri, mpcdf, leicester, vsc_ugent, create, sage, cambridge, jex, podman, ebi_codon, cheaha, xanadu, nyu_hpc, test, marjorie, computerome, ucd_sonic, seg_globe, sanger, dkfz, pasteur, einstein, ethz_euler, m3c, test_full, imb, ucl_cscluster, tuos_stanage, azurebatch, hki, crukmi, csiro_petrichor, qmul_apocrita, docker, engaging, gis, hypatia, psmn, eva, nygc, fgcz, conda, crg, singularity, mpcdf_viper, self_hosted_runner, tufts, uw_hyak_pedslabs, debug, genouest, cbe, phoenix, gitpod, seawulf, uod_hpc, fub_curta, uct_hpc, aws_tower, binac]
Aug-20 13:41:52.099 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 from script declararion
Aug-20 13:41:52.100 [main] INFO  nextflow.cli.CmdRun - Launching `https://github.com/nf-core/oncoanalyser` [spontaneous_wilson] DSL2 - revision: 0881ae9936 [v0.3.1]
Aug-20 13:41:52.111 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; plugins-dir=/home/crunchshell/.nextflow/plugins; core-plugins: nf-amazon@1.7.2,nf-azure@0.13.2,nf-console@1.0.3,nf-ga4gh@1.0.3,nf-google@1.1.4,nf-sqldb@0.4.0,nf-tower@1.4.0
Aug-20 13:41:52.114 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Aug-20 13:41:52.121 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Aug-20 13:41:52.121 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Aug-20 13:41:52.123 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Aug-20 13:41:52.134 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Aug-20 13:41:52.195 [main] DEBUG nextflow.Session - Session uuid: 68398e2b-afb4-49ab-ad82-94da889cc812
Aug-20 13:41:52.195 [main] DEBUG nextflow.Session - Run name: spontaneous_wilson
Aug-20 13:41:52.196 [main] DEBUG nextflow.Session - Executor pool size: 188
Aug-20 13:41:52.231 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 22.04.3 build 5703
  Created: 18-05-2022 19:22 UTC (21:22 CEST)
  System: Linux 6.5.0-44-generic
  Runtime: Groovy 3.0.10 on OpenJDK 64-Bit Server VM 11.0.24+8-post-Ubuntu-1ubuntu322.04
  Encoding: UTF-8 (UTF-8)
  Process: 3751968@rembrandt [127.0.1.1]
  CPUs: 188 - Mem: 661.3 GB (16.8 GB) - Swap: 2 GB (1.8 GB)
Aug-20 13:41:52.268 [main] DEBUG nextflow.Session - Work-dir: /path/N2N_mock/work [nfs]
Aug-20 13:41:52.268 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/crunchshell/.nextflow/assets/nf-core/oncoanalyser/bin
Aug-20 13:41:52.281 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Aug-20 13:41:52.299 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Aug-20 13:41:52.390 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Aug-20 13:41:52.402 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 189; maxThreads: 1000
Aug-20 13:41:52.495 [main] DEBUG nextflow.Session - Session start invoked
Aug-20 13:41:52.506 [main] DEBUG nextflow.trace.TraceFileObserver - Flow starting -- trace file: /path/N2N_mock/wgs/result_calls/pipeline_info/execution_trace_2024-08-20_13-41-51.txt
Aug-20 13:41:52.521 [main] DEBUG nextflow.Session - Using default localLib path: /home/crunchshell/.nextflow/assets/nf-core/oncoanalyser/lib
Aug-20 13:41:52.526 [main] DEBUG nextflow.Session - Adding to the classpath library: /home/crunchshell/.nextflow/assets/nf-core/oncoanalyser/lib
Aug-20 13:41:52.527 [main] DEBUG nextflow.Session - Adding to the classpath library: /home/crunchshell/.nextflow/assets/nf-core/oncoanalyser/lib/nfcore_external_java_deps.jar
Aug-20 13:41:54.616 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Aug-20 13:41:54.908 [main] INFO  nextflow.Nextflow - 

-[2m----------------------------------------------------[0m-
                                        [0;32m,--.[0;30m/[0;32m,-.[0m
[0;34m        ___     __   __   __   ___     [0;32m/,-._.--~'[0m
[0;34m  |\ | |__  __ /  ` /  \ |__) |__         [0;33m}  {[0m
[0;34m  | \| |       \__, \__/ |  \ |___     [0;32m\`-._,-`-,[0m
                                        [0;32m`._,._,'[0m
[0;35m  nf-core/oncoanalyser v0.3.1[0m
-[2m----------------------------------------------------[0m-
[1mCore Nextflow options[0m
  [0;34mrevision                       : [0;32mv0.3.1[0m
  [0;34mrunName                        : [0;32mspontaneous_wilson[0m
  [0;34mcontainerEngine                : [0;32mdocker[0m
  [0;34mlaunchDir                      : [0;32m/path/N2N_mock[0m
  [0;34mworkDir                        : [0;32m/path/N2N_mock/work[0m
  [0;34mprojectDir                     : [0;32m/home/crunchshell/.nextflow/assets/nf-core/oncoanalyser[0m
  [0;34muserName                       : [0;32mcrunchshell[0m
  [0;34mprofile                        : [0;32mdocker[0m
  [0;34mconfigFiles                    : [0;32m/home/crunchshell/.nextflow/assets/nf-core/oncoanalyser/nextflow.config[0m

[1mInput/output options[0m
  [0;34minput                          : [0;32m/path/N2N_mock/wgs/samplesheet.csv[0m
  [0;34moutdir                         : [0;32m/path/N2N_mock/wgs/result_calls/[0m

[1mOther options[0m
  [0;34mmode                           : [0;32mwgts[0m
  [0;34misofox_read_length             : [0;32m151[0m

[1mReference data options[0m
  [0;34mgenome                         : [0;32mGRCh37_hmf[0m
  [0;34mref_data_hmf_data_path         : [0;32mhttps://pub-29f2e5b2b7384811bdbbcba44f8b5083.r2.dev/hmf_reference_data/hmftools/5.34_37--0.tar.gz[0m
  [0;34mref_data_virusbreakenddb_path  : [0;32mhttps://pub-29f2e5b2b7384811bdbbcba44f8b5083.r2.dev/virusbreakend/virusbreakenddb_20210401.tar.gz[0m
  [0;34mref_data_genome_fasta          : [0;32mhttps://pub-29f2e5b2b7384811bdbbcba44f8b5083.r2.dev/genomes/GRCh37_hmf/Homo_sapiens.GRCh37.GATK.illumina.fasta[0m
  [0;34mref_data_genome_fai            : [0;32mhttps://pub-29f2e5b2b7384811bdbbcba44f8b5083.r2.dev/genomes/GRCh37_hmf/samtools_index/1.16/Homo_sapiens.GRCh37.GATK.illumina.fasta.fai[0m
  [0;34mref_data_genome_dict           : [0;32mhttps://pub-29f2e5b2b7384811bdbbcba44f8b5083.r2.dev/genomes/GRCh37_hmf/samtools_index/1.16/Homo_sapiens.GRCh37.GATK.illumina.fasta.dict[0m
  [0;34mref_data_genome_bwa_index      : [0;32mhttps://pub-29f2e5b2b7384811bdbbcba44f8b5083.r2.dev/genomes/GRCh37_hmf/bwa_index/0.7.17-r1188.tar.gz[0m
  [0;34mref_data_genome_bwa_index_image: [0;32mhttps://pub-29f2e5b2b7384811bdbbcba44f8b5083.r2.dev/genomes/GRCh37_hmf/bwa_index_image/0.7.17-r1188/Homo_sapiens.GRCh37.GATK.illumina.fasta.img[0m
  [0;34mref_data_genome_gridss_index   : [0;32mhttps://pub-29f2e5b2b7384811bdbbcba44f8b5083.r2.dev/genomes/GRCh37_hmf/gridss_index/2.13.2/Homo_sapiens.GRCh37.GATK.illumina.fasta.gridsscache[0m

!! Only displaying parameters that differ from the pipeline defaults !!
-[2m----------------------------------------------------[0m-
If you use nf-core/oncoanalyser for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/nf-core/oncoanalyser/blob/master/CITATIONS.md
-[2m----------------------------------------------------[0m-
Aug-20 13:41:55.548 [main] ERROR nextflow.Nextflow - received invalid file type: 'fastq'. Valid options are:
  - bam
  - bai
  - amber_dir
  - bamtools
  - cobalt_dir
  - gridss_vcf
  - gridss_vcf_tbi
  - gripss_vcf
  - gripss_vcf_tbi
  - gripss_unfiltered_vcf
  - gripss_unfiltered_vcf_tbi
  - isofox_dir
  - lilac_dir
  - linx_anno_dir
  - pave_vcf
  - purple_dir
  - sage_vcf
  - sage_vcf_tbi
  - sage_append_vcf
  - virusinterpreter_dir
  - chord_dir
  - sigs_dir
  - cuppa_dir
  - flagstat
  - linx_plot_dir
  - sage_dir

### System information

Nextflow v22.04.3
HPC
local
Docker
linux
-r v0.3.1

**Comment by scwatts** [comment]
Hi @jkneppers, FASTQ input is only supported from the 0.4.0 oncoanalyser release so the error message you're seeing with 0.3.1 is expected.

I would recommend using the `dev` branch since I'll be making the 1.0.0 release from this within the next week or so, and it contains several important fixes.

Please try with again using `-revision dev` and reopen the issue if that doesn't work!
