### ISSUE TITLE
Compatibility of IonTorrent BAM Files for HRD Analysis with nf-core/oncoanalyser

### ISSUE THREAD

**Issue by Sadiki-Noureddine** [nf-core/oncoanalyser#92]
### Description of the bug

Hello,

I am interested in using the nf-core/oncoanalyser pipeline for homologous recombination deficiency (HRD) analysis. I have a couple of questions regarding the compatibility and usage of the pipeline with specific data:

1.    Compatibility with IonTorrent BAM Files: Is it possible to use nf-core/oncoanalyser to analyze BAM files generated by the IonTorrent platform? If so, are there any specific considerations or adjustments that need to be made when importing these files into the pipeline?

2.    Using the Oncomine Comprehensive Assay Plus (Thermo Fisher): I would like to know if it's feasible to use nf-core/oncoanalyser for HRD analysis with data from the Oncomine Comprehensive Assay Plus panel by Thermo Fisher. Although the documentation mentions support for the TSO500 panel, I am curious whether a similar analysis can be performed with the Oncomine Comprehensive Assay Plus panel, and what modifications might be necessary.

Thank you for your assistance and for the excellent work on this pipeline.

Best regards,

**Comment by scwatts** [comment]
These questions have been addressed in an email with the Hartwig folks, closing the issue for now
